### ISSUE TITLE
Uncaught TypeError: Cannot read property 'click' of undefined

### ISSUE THREAD

**Issue by bugwelle** [richadams/jquery-taphold#1]
So, I get this error:
`Uncaught TypeError: Cannot read property 'click' of undefined`
I fixed it by adding `$elem.data("events")` to the if statement in line 15 in taphold.js.
I don't know why I got this error, but I hope, you can implement this into the script :)

Greetings from Germany, Andre

**Comment by richadams** [comment]
Have added the extra check for `$elem.data("events")`, thanks for the bug report!

**Comment by bugwelle** [comment]
Thanks :)
:+1:
