### ISSUE TITLE
Taphold event triggering twice

### ISSUE THREAD

**Issue by bugwelle** [richadams/jquery-taphold#3]
Hello,
I like your jQuery plugin, but I'm having some problems with it.

jsFiddle: http://jsfiddle.net/AndreM/kQKyq/
(my JavaScript code is at the end; I inserted your plugin there, because GitHub is no CDN :D )

The content of the `p` tag after making a long tap is:

```
TAPHOLDTAPHOLD
```

This only happens if touch events in Chrome are enabled (via the console). It's because the script is listening to both, mouse- and touchevents at the same time, and Chrome triggers both.

You can solve this bug by changing and adding a little bit of code at the end of `taphold.js`:

``` javascript
// Checking for touch support
var touchSupported =  ('ontouchstart' in window) || // works on most browsers
    ('onmsgesturechange' in window); // Mircosoft

var START_EVENT = touchSupported ? 'touchstart' : 'mousedown',
    MOVE_EVENT = touchSupported ? 'touchmove' : 'mousemove',
    END_EVENT = touchSupported ? 'touchend' : 'mouseup';

var taphold = $.event.special.taphold =
{
    setup: function(data)
    {
        $(this).bind(START_EVENT,  data, startHandler)
               .bind(MOVE_EVENT,    stopHandler)
               .bind(END_EVENT, leaveHandler);
    },
    teardown: function(namespaces)
    {
        $(this).unbind(START_EVENT,  startHandler)
               .unbind(MOVE_EVENT,    stopHandler)
               .unbind(END_EVENT, leaveHandler);
    }
};
```

It would be great if you could merge this into your project :) 

Greetings from Germany,
Andre

**Comment by richadams** [comment]
Thanks for the bug report and fix! I've added your fix into the code.
