### ISSUE TITLE
Click events gets triggered after a taphold on desktop

### ISSUE THREAD

**Issue by ghost** [richadams/jquery-taphold#4]
Hi Rich Adams,

I ran into an issue; A click event gets triggered even tough the taphold event was already fired. Weird enough this only happens on my desktop, as it seems to work fine on my ipad/android.

Is there a solution to this?

``` javascript
    $('#logo').bind({
        'click': function(){
            bugline('Logo clicked.');
            openwindow('home');
        },
        'taphold contextmenu': function(){
            bugline('Logo long- / rightclicked.');
            openwindow('about');
            return false;
        }
    });
```

Also using the build in click trigger doesn't seem to work correctly:

``` javascript
    $("#logo").on("taphold", {
        clickHandler: function(){
            bugline('Logo clicked.');
            openwindow('home');
        }
    },
    function(){
        bugline('Logo longclicked.');
        openwindow('about');
    });
```

It works fine the first time. After the first taphold the click event is immediately triggered at the start of the second taphold.

**Comment by richadams** [comment]
What browser are you using on your desktop? I wasn't able to reproduce this in Chrome. The only weirdness I had was with the first example, where a contextmenu click also triggered a normal click.

**Comment by ghost** [comment]
Google Chrome Version 28.0.1500.72 m (Windows 7), but I have the same problem in IE and FF.

Maybe I'm doing something wrong, but I've found similar issues on the web.

**Comment by richadams** [comment]
I'm still unable to reproduce this in my tests. What version of jQuery are you using? Is this an issue any more?
