### ISSUE TITLE
Add to bower.io

### ISSUE THREAD

**Issue by andres-torres-marroquin** [richadams/jquery-taphold#7]

**Comment by richadams** [comment]
It's a single .js file... does this really need to be deployed with a package manager? Seems like overkill, just copy the file into your project and be done with it.

**Comment by andres-torres-marroquin** [comment]
Think it as a requirement for a project. There I paste you some benefits of add it to bower.
- Simplify what might be called declarative dependency management; i.e. you declare your dependencies in bower.json so that other things can determine them easily
  No need to commit dependencies to version control
- Semantic versioning is used to help define a range of acceptable versions for a dependency, which makes it easy to update to newer versions within the defined range
- No need to locate various builds (debug, minified, etc)
- Simple to use different builds of a dependency for dev vs. prod

_Extracted from: https://programmers.stackexchange.com/questions/224828/why-should-i-use-bower_
